# 07b - Optuna sobre LightGBM + BERT/SVD

Este notebook continua el apartado de modelado despues de seleccionar `lightgbm_final_bert` como arquitectura ganadora en el notebook 07.

Objetivo: comprobar si una busqueda adicional de hiperparametros mejora el modelo ganador usando solo `train`, validacion cruzada agrupada por paciente y predicciones OOF. El test temporal no se carga ni se utiliza en este notebook.

## 1. Protocolo

- Modelo estudiado: LightGBM con variables tabulares finales + componentes BERT/SVD.
- Datos: `X_train_final`, `bert_embeddings_train`, `y_train`, `groups_train`, `sample_weights_train`.
- Validacion: `StratifiedGroupKFold` agrupado por paciente.
- Objetivo Optuna: maximizar Macro F1 OOF medio.
- Metrica principal del modelo congelado actual: Macro F1 OOF = `0.567940`.
- Regla metodologica: no se usa test temporal para seleccionar hiperparametros, features, thresholds ni politica.

In [1]:
# ruff: noqa: E402, I001
import json
import sys
import time
import warnings
from pathlib import Path
from typing import Any

import lightgbm as lgb
import numpy as np
import optuna
import pandas as pd
from sklearn.metrics import f1_score, precision_recall_fscore_support
from sklearn.model_selection import StratifiedGroupKFold

warnings.filterwarnings("ignore")

PROJECT_ROOT = Path.cwd()
while not (PROJECT_ROOT / "pyproject.toml").exists():
    if PROJECT_ROOT.parent == PROJECT_ROOT:
        raise RuntimeError("No se pudo localizar la raiz del proyecto.")
    PROJECT_ROOT = PROJECT_ROOT.parent

SRC_DIR = PROJECT_ROOT / "src"
if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

from triaje_ia.config import DATA_PROCESSED, MODELS_DIR, REPORTS_DIR

RANDOM_STATE = 42
CLASSES = np.array([1, 2, 3, 4, 5])
BASELINE_MACRO_F1 = 0.567940
N_SPLITS = 5
N_TRIALS = 60
TIMEOUT_SECONDS = None

OUT_DIR = REPORTS_DIR / "hyperparameter_tuning"
OUT_DIR.mkdir(parents=True, exist_ok=True)

STUDY_NAME = "lgbm_bert_optuna_macro_f1_oof"
STORAGE_URL = f"sqlite:///{(OUT_DIR / 'lgbm_bert_optuna_study.db').as_posix()}"

print(f"Proyecto: {PROJECT_ROOT}")
print(f"Salida: {OUT_DIR}")

Proyecto: c:\Users\CARLOS\triaje-ia-tfg
Salida: C:\Users\CARLOS\triaje-ia-tfg\reports\hyperparameter_tuning

c:\Users\CARLOS\triaje-ia-tfg\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## 2. Carga de train y comprobaciones

Se reconstruye la misma matriz del modelo final, pero solo para train. La lista de columnas se carga desde `models/feature_list.json` para respetar el contrato congelado del modelo actual.

In [2]:
required = [
    DATA_PROCESSED / "X_train_final.parquet",
    DATA_PROCESSED / "bert_embeddings_train.parquet",
    DATA_PROCESSED / "y_train.parquet",
    DATA_PROCESSED / "groups_train.npy",
    DATA_PROCESSED / "sample_weights_train.npy",
    MODELS_DIR / "feature_list.json",
]
missing = [path for path in required if not path.exists()]
if missing:
    raise FileNotFoundError("Faltan artefactos: " + ", ".join(map(str, missing)))

feature_payload = json.loads((MODELS_DIR / "feature_list.json").read_text(encoding="utf-8"))
feature_list = feature_payload["features"]

X_tab = pd.read_parquet(DATA_PROCESSED / "X_train_final.parquet").reset_index(drop=True)
X_bert = pd.read_parquet(DATA_PROCESSED / "bert_embeddings_train.parquet").reset_index(drop=True)
X_train = pd.concat([X_tab, X_bert], axis=1)[feature_list]
y_train = pd.read_parquet(DATA_PROCESSED / "y_train.parquet").squeeze().astype(int).reset_index(drop=True)
groups_train = np.load(DATA_PROCESSED / "groups_train.npy")
sample_weights_train = np.load(DATA_PROCESSED / "sample_weights_train.npy")

assert X_train.shape[0] == y_train.shape[0] == len(groups_train) == len(sample_weights_train)
assert X_train.shape[1] == len(feature_list) == 79
assert y_train.isin(CLASSES).all()
assert (sample_weights_train > 0).all() and not np.isnan(sample_weights_train).any()

print("X_train:", X_train.shape)
print("y_train:", y_train.shape)
print("Pacientes/grupos:", pd.Series(groups_train).nunique())
print("Distribucion train:")
print(y_train.value_counts(normalize=True).sort_index().round(4))

X_train: (334480, 79)
y_train: (334480,)
Pacientes/grupos: 168596
Distribucion train:
acuity
1    0.0579
2    0.3326
3    0.5372
4    0.0695
5    0.0028
Name: proportion, dtype: float64

## 3. Analisis del desbalance en train

Aunque Acuity 1 tiene un porcentaje visible en train, el problema sigue estando desbalanceado: la clase mayoritaria es Acuity 3 y la clase Acuity 5 es extremadamente minoritaria. Este analisis justifica el uso de Macro F1, metricas por clase y `sample_weights_train`.

La tabla siguiente combina frecuencia real, ratio frente a la clase mayoritaria y peso efectivo tras aplicar `sample_weights_train`.

In [3]:
counts = y_train.value_counts().sort_index()
pct = counts / len(y_train) * 100
majority = counts.max()

imbalance_rows = []
for acuity in counts.index:
    mask = y_train.to_numpy() == acuity
    imbalance_rows.append(
        {
            "acuity": int(acuity),
            "n": int(counts.loc[acuity]),
            "pct_train": float(pct.loc[acuity]),
            "ratio_mayoritaria_vs_clase": float(majority / counts.loc[acuity]),
            "sample_weight_medio": float(sample_weights_train[mask].mean()),
            "peso_total_clase": float(sample_weights_train[mask].sum()),
            "pct_efectivo_tras_pesos": float(sample_weights_train[mask].sum() / sample_weights_train.sum() * 100),
        }
    )

imbalance_df = pd.DataFrame(imbalance_rows)
display(imbalance_df)

print(f"Ratio mayoria/minoria: {counts.max():,} / {counts.min():,} = {counts.max() / counts.min():.1f}:1")
print(f"Acuity 1-2 en train: {pct.loc[[1, 2]].sum():.2f}%")
print(f"Acuity 4-5 en train: {pct.loc[[4, 5]].sum():.2f}%")
print(f"Acuity 5 por fold aprox. en CV de 5 folds: {counts.loc[5] / 5:.1f} casos")

,acuity,n,pct_train,ratio_mayoritaria_vs_clase,sample_weight_medio,peso_total_clase,pct_efectivo_tras_pesos
0,1,19371,5.791378,9.275463,2.226040,43120.627355,12.891840
1,2,111262,33.264171,1.614882,0.928829,103343.337082,30.896716
2,3,179675,53.717711,1.000000,0.730912,131326.653291,39.262932
3,4,23240,6.948099,7.731282,2.032315,47230.996869,14.120724
4,5,932,0.278641,192.784335,10.148482,9458.385403,2.827788

Ratio mayoria/minoria: 179,675 / 932 = 192.8:1
Acuity 1-2 en train: 39.06%
Acuity 4-5 en train: 7.23%
Acuity 5 por fold aprox. en CV de 5 folds: 186.4 casos

## 4. Helpers de metricas

Optuna optimiza Macro F1. Tambien se guardan precision y recall de Acuity 1 y 2 para asegurar que una mejora global no empeora de forma preocupante las clases mas sensibles.

In [4]:
def metricas_oof(y_true: pd.Series | np.ndarray, y_pred: np.ndarray) -> dict[str, float]:
    precision, recall, f1, _ = precision_recall_fscore_support(
        y_true, y_pred, labels=CLASSES, zero_division=0
    )
    return {
        "macro_f1": float(f1_score(y_true, y_pred, average="macro", zero_division=0)),
        "recall_a1": float(recall[0]),
        "precision_a1": float(precision[0]),
        "recall_a2": float(recall[1]),
        "precision_a2": float(precision[1]),
        "f1_a1": float(f1[0]),
        "f1_a2": float(f1[1]),
    }


def fixed_lgbm_params() -> dict[str, Any]:
    return {
        "objective": "multiclass",
        "num_class": 5,
        "metric": "multi_logloss",
        "boosting_type": "gbdt",
        "random_state": RANDOM_STATE,
        "n_jobs": -1,
        "verbose": -1,
        "subsample_freq": 1,
    }


def suggest_lgbm_params(trial: optuna.Trial) -> dict[str, Any]:
    params = fixed_lgbm_params()
    params.update(
        {
        "num_leaves": trial.suggest_int("num_leaves", 48, 192),
        "max_depth": trial.suggest_int("max_depth", 5, 12),
        "min_data_in_leaf": trial.suggest_int("min_data_in_leaf", 10, 120),
        "reg_alpha": trial.suggest_float("reg_alpha", 1e-4, 3.0, log=True),
        "reg_lambda": trial.suggest_float("reg_lambda", 1e-3, 8.0, log=True),
        "min_gain_to_split": trial.suggest_float("min_gain_to_split", 0.0, 2.0),
        "subsample": trial.suggest_float("subsample", 0.70, 1.0),
        "colsample_bytree": trial.suggest_float("colsample_bytree", 0.50, 0.95),
        "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.06, log=True),
        "n_estimators": trial.suggest_int("n_estimators", 350, 1200),
        }
    )
    return params


def params_from_completed_trial(trial: optuna.trial.FrozenTrial) -> dict[str, Any]:
    params = fixed_lgbm_params()
    params.update(trial.params)
    return params


def evaluate_params(params: dict[str, Any], trial: optuna.Trial | None = None) -> dict[str, Any]:
    cv = StratifiedGroupKFold(n_splits=N_SPLITS, shuffle=False)
    oof_pred = np.zeros(len(y_train), dtype=int)
    fold_scores: list[float] = []
    best_iterations: list[int] = []

    for fold, (idx_tr, idx_val) in enumerate(cv.split(X_train, y_train, groups_train), start=1):
        model = lgb.LGBMClassifier(**params)
        model.fit(
            X_train.iloc[idx_tr],
            y_train.iloc[idx_tr] - 1,
            sample_weight=sample_weights_train[idx_tr],
            eval_set=[(X_train.iloc[idx_val], y_train.iloc[idx_val] - 1)],
            eval_sample_weight=[sample_weights_train[idx_val]],
            callbacks=[lgb.early_stopping(50, verbose=False)],
        )
        pred = model.predict(X_train.iloc[idx_val]) + 1
        oof_pred[idx_val] = pred
        fold_macro = float(f1_score(y_train.iloc[idx_val], pred, average="macro", zero_division=0))
        fold_scores.append(fold_macro)
        best_iterations.append(int(model.best_iteration_ or params["n_estimators"]))

        if trial is not None:
            trial.report(float(np.mean(fold_scores)), step=fold)
            if trial.should_prune():
                raise optuna.TrialPruned()

    metrics = metricas_oof(y_train, oof_pred)
    metrics.update(
        {
            "fold_macro_f1_mean": float(np.mean(fold_scores)),
            "fold_macro_f1_std": float(np.std(fold_scores)),
            "best_iteration_mean": float(np.mean(best_iterations)),
            "best_iteration_std": float(np.std(best_iterations)),
        }
    )
    return metrics

## 5. Busqueda Optuna

El estudio se guarda en SQLite para poder reanudarlo si se interrumpe. Cada trial entrena cinco folds y calcula OOF sobre train.

In [5]:
def objective(trial: optuna.Trial) -> float:
    params = suggest_lgbm_params(trial)
    start = time.perf_counter()
    metrics = evaluate_params(params, trial=trial)
    elapsed = time.perf_counter() - start

    for key, value in metrics.items():
        trial.set_user_attr(key, value)
    trial.set_user_attr("elapsed_seconds", float(elapsed))

    return metrics["macro_f1"]


sampler = optuna.samplers.TPESampler(seed=RANDOM_STATE, multivariate=True)
pruner = optuna.pruners.MedianPruner(n_startup_trials=8, n_warmup_steps=2)
study = optuna.create_study(
    study_name=STUDY_NAME,
    storage=STORAGE_URL,
    direction="maximize",
    sampler=sampler,
    pruner=pruner,
    load_if_exists=True,
)

study.optimize(objective, n_trials=N_TRIALS, timeout=TIMEOUT_SECONDS, show_progress_bar=True)

print("Best trial:", study.best_trial.number)
print("Best Macro F1:", study.best_value)
print("Best params:")
print(json.dumps(study.best_trial.params, indent=2))

[I 2026-06-06 18:12:03,928] Using an existing study with name 'lgbm_bert_optuna_macro_f1_oof' instead of creating a new one.
Best trial: 1. Best value: 0.566552:   2%|▏         | 1/60 [04:29<4:24:41, 269.19s/it]

[I 2026-06-06 18:16:33,102] Trial 1 finished with value: 0.5665522057115873 and parameters: {'num_leaves': 102, 'max_depth': 12, 'min_data_in_leaf': 91, 'reg_alpha': 0.04789240251631178, 'reg_lambda': 0.004064010237521863, 'min_gain_to_split': 0.3119890406724053, 'subsample': 0.7174250836504598, 'colsample_bytree': 0.8897792655987208, 'learning_rate': 0.0293601586511158, 'n_estimators': 952}. Best is trial 1 with value: 0.5665522057115873.

Best trial: 2. Best value: 0.567349:   3%|▎         | 2/60 [10:05<4:58:08, 308.42s/it]

[I 2026-06-06 18:22:08,988] Trial 2 finished with value: 0.5673487483470393 and parameters: {'num_leaves': 50, 'max_depth': 12, 'min_data_in_leaf': 102, 'reg_alpha': 0.0008926227381843736, 'reg_lambda': 0.005124826994072942, 'min_gain_to_split': 0.36680901970686763, 'subsample': 0.7912726728878613, 'colsample_bytree': 0.7361403942345071, 'learning_rate': 0.021682959386691958, 'n_estimators': 597}. Best is trial 2 with value: 0.5673487483470393.

Best trial: 2. Best value: 0.567349:   5%|▌         | 3/60 [13:17<4:02:41, 255.46s/it]

[I 2026-06-06 18:25:21,438] Trial 3 finished with value: 0.5632120543108631 and parameters: {'num_leaves': 136, 'max_depth': 6, 'min_data_in_leaf': 42, 'reg_alpha': 0.004367635583109819, 'reg_lambda': 0.06026736292333659, 'min_gain_to_split': 1.5703519227860272, 'subsample': 0.7599021346475079, 'colsample_bytree': 0.7314054972861253, 'learning_rate': 0.028906009262484492, 'n_estimators': 389}. Best is trial 2 with value: 0.5673487483470393.

Best trial: 2. Best value: 0.567349:   7%|▋         | 4/60 [19:34<4:43:08, 303.37s/it]

[I 2026-06-06 18:31:38,239] Trial 4 finished with value: 0.5667751726649473 and parameters: {'num_leaves': 136, 'max_depth': 6, 'min_data_in_leaf': 17, 'reg_alpha': 1.7712326416857447, 'reg_lambda': 5.874199871058072, 'min_gain_to_split': 1.6167946962329223, 'subsample': 0.7913841307520112, 'colsample_bytree': 0.5439524513028727, 'learning_rate': 0.03407507223305134, 'n_estimators': 724}. Best is trial 2 with value: 0.5673487483470393.

Best trial: 2. Best value: 0.567349:   8%|▊         | 5/60 [23:49<4:22:09, 285.99s/it]

[I 2026-06-06 18:35:53,435] Trial 5 finished with value: 0.5672958766847639 and parameters: {'num_leaves': 65, 'max_depth': 8, 'min_data_in_leaf': 13, 'reg_alpha': 1.1779794101330692, 'reg_lambda': 0.010233909096936954, 'min_gain_to_split': 1.325044568707964, 'subsample': 0.7935133228268233, 'colsample_bytree': 0.7340306095300149, 'learning_rate': 0.026633196140794114, 'n_estimators': 507}. Best is trial 2 with value: 0.5673487483470393.

Best trial: 6. Best value: 0.56802:  10%|█         | 6/60 [31:43<5:15:04, 350.08s/it]

[I 2026-06-06 18:43:47,901] Trial 6 finished with value: 0.5680198804479502 and parameters: {'num_leaves': 188, 'max_depth': 11, 'min_data_in_leaf': 114, 'reg_alpha': 1.0144964926243927, 'reg_lambda': 0.21560430117882007, 'min_gain_to_split': 1.8437484700462337, 'subsample': 0.7265477506155759, 'colsample_bytree': 0.5881922880886153, 'learning_rate': 0.010844103935147875, 'n_estimators': 626}. Best is trial 6 with value: 0.5680198804479502.

Best trial: 7. Best value: 0.568652:  12%|█▏        | 7/60 [40:33<6:00:59, 408.67s/it]

[I 2026-06-06 18:52:37,201] Trial 7 finished with value: 0.568651612260586 and parameters: {'num_leaves': 104, 'max_depth': 7, 'min_data_in_leaf': 101, 'reg_alpha': 0.003955741482490562, 'reg_lambda': 0.01248856882966007, 'min_gain_to_split': 1.085392166316497, 'subsample': 0.7422772674924287, 'colsample_bytree': 0.8609886413393177, 'learning_rate': 0.0114290906303734, 'n_estimators': 1189}. Best is trial 7 with value: 0.568651612260586.

Best trial: 7. Best value: 0.568652:  13%|█▎        | 8/60 [45:09<5:17:43, 366.60s/it]

[I 2026-06-06 18:57:13,725] Trial 8 finished with value: 0.5626940501114818 and parameters: {'num_leaves': 159, 'max_depth': 6, 'min_data_in_leaf': 10, 'reg_alpha': 0.4476305242680421, 'reg_lambda': 0.5740210529664587, 'min_gain_to_split': 1.4580143360819746, 'subsample': 0.9313811040057838, 'colsample_bytree': 0.5333200932803407, 'learning_rate': 0.01900818083017492, 'n_estimators': 448}. Best is trial 7 with value: 0.568651612260586.

Best trial: 7. Best value: 0.568652:  15%|█▌        | 9/60 [48:26<4:26:34, 313.62s/it]

[I 2026-06-06 19:00:30,855] Trial 9 finished with value: 0.5677009959577413 and parameters: {'num_leaves': 173, 'max_depth': 9, 'min_data_in_leaf': 46, 'reg_alpha': 0.00019255661420887883, 'reg_lambda': 0.016360327233219233, 'min_gain_to_split': 0.6503666440534941, 'subsample': 0.9188818535014192, 'colsample_bytree': 0.7869008621098459, 'learning_rate': 0.04902139942455276, 'n_estimators': 751}. Best is trial 7 with value: 0.568651612260586.

Best trial: 7. Best value: 0.568652:  17%|█▋        | 10/60 [50:47<3:36:53, 260.27s/it]

[I 2026-06-06 19:02:51,662] Trial 10 pruned.

Best trial: 7. Best value: 0.568652:  18%|█▊        | 11/60 [57:44<4:11:46, 308.31s/it]

[I 2026-06-06 19:09:48,885] Trial 11 finished with value: 0.567847664489536 and parameters: {'num_leaves': 125, 'max_depth': 7, 'min_data_in_leaf': 73, 'reg_alpha': 0.2217999137353056, 'reg_lambda': 0.0020499057087558026, 'min_gain_to_split': 1.5516922726512514, 'subsample': 0.7723827965760627, 'colsample_bytree': 0.8393872283362652, 'learning_rate': 0.01748470695678148, 'n_estimators': 1167}. Best is trial 7 with value: 0.568651612260586.

Best trial: 7. Best value: 0.568652:  20%|██        | 12/60 [1:04:01<4:23:20, 329.18s/it]

[I 2026-06-06 19:16:05,803] Trial 12 finished with value: 0.5684158985481287 and parameters: {'num_leaves': 188, 'max_depth': 11, 'min_data_in_leaf': 108, 'reg_alpha': 0.4234117481379165, 'reg_lambda': 0.22952219868673085, 'min_gain_to_split': 1.9162275769866404, 'subsample': 0.7576451150843404, 'colsample_bytree': 0.56793486135441, 'learning_rate': 0.01077830553366806, 'n_estimators': 449}. Best is trial 7 with value: 0.568651612260586.

Best trial: 7. Best value: 0.568652:  22%|██▏       | 13/60 [1:13:15<5:11:10, 397.24s/it]

[I 2026-06-06 19:25:19,662] Trial 13 finished with value: 0.5681336375437173 and parameters: {'num_leaves': 131, 'max_depth': 9, 'min_data_in_leaf': 78, 'reg_alpha': 0.002146587609798014, 'reg_lambda': 0.24034254203104158, 'min_gain_to_split': 1.200802754644924, 'subsample': 0.7358907363530564, 'colsample_bytree': 0.8047419866347734, 'learning_rate': 0.011030859264274821, 'n_estimators': 1076}. Best is trial 7 with value: 0.568651612260586.

Best trial: 7. Best value: 0.568652:  23%|██▎       | 14/60 [1:21:02<5:20:40, 418.26s/it]

[I 2026-06-06 19:33:06,506] Trial 14 finished with value: 0.5682690465050377 and parameters: {'num_leaves': 59, 'max_depth': 8, 'min_data_in_leaf': 114, 'reg_alpha': 0.006412621866835859, 'reg_lambda': 0.015819911180822273, 'min_gain_to_split': 0.7642022300165954, 'subsample': 0.7033027249717241, 'colsample_bytree': 0.7390053223734432, 'learning_rate': 0.01398933355896561, 'n_estimators': 1177}. Best is trial 7 with value: 0.568651612260586.

Best trial: 7. Best value: 0.568652:  25%|██▌       | 15/60 [1:24:11<4:21:53, 349.20s/it]

[I 2026-06-06 19:36:15,643] Trial 15 pruned.

Best trial: 7. Best value: 0.568652:  27%|██▋       | 16/60 [1:32:13<4:45:17, 389.03s/it]

[I 2026-06-06 19:44:17,174] Trial 16 finished with value: 0.5673813285424292 and parameters: {'num_leaves': 113, 'max_depth': 6, 'min_data_in_leaf': 66, 'reg_alpha': 0.0015989896634274893, 'reg_lambda': 0.004602078970720804, 'min_gain_to_split': 0.6995567436355821, 'subsample': 0.7858734220911531, 'colsample_bytree': 0.8580689608929224, 'learning_rate': 0.0185464666533786, 'n_estimators': 1068}. Best is trial 7 with value: 0.568651612260586.

Best trial: 7. Best value: 0.568652:  28%|██▊       | 17/60 [1:35:11<3:53:29, 325.80s/it]

[I 2026-06-06 19:47:15,913] Trial 17 pruned.

Best trial: 7. Best value: 0.568652:  30%|███       | 18/60 [1:37:45<3:11:44, 273.91s/it]

[I 2026-06-06 19:49:49,044] Trial 18 pruned.

Best trial: 7. Best value: 0.568652:  32%|███▏      | 19/60 [1:40:28<2:44:25, 240.62s/it]

[I 2026-06-06 19:52:32,102] Trial 19 pruned.

Best trial: 7. Best value: 0.568652:  33%|███▎      | 20/60 [1:42:47<2:20:11, 210.28s/it]

[I 2026-06-06 19:54:51,669] Trial 20 pruned.

Best trial: 7. Best value: 0.568652:  35%|███▌      | 21/60 [1:52:23<3:28:03, 320.08s/it]

[I 2026-06-06 20:04:27,743] Trial 21 finished with value: 0.5679959310052359 and parameters: {'num_leaves': 121, 'max_depth': 8, 'min_data_in_leaf': 85, 'reg_alpha': 1.418465822692253, 'reg_lambda': 0.17985697848315768, 'min_gain_to_split': 0.5512921081936799, 'subsample': 0.7104598338524216, 'colsample_bytree': 0.8838193540587894, 'learning_rate': 0.010071979156025227, 'n_estimators': 1187}. Best is trial 7 with value: 0.568651612260586.

Best trial: 7. Best value: 0.568652:  37%|███▋      | 22/60 [1:59:15<3:40:09, 347.61s/it]

[I 2026-06-06 20:11:19,572] Trial 22 finished with value: 0.5682464494525492 and parameters: {'num_leaves': 60, 'max_depth': 8, 'min_data_in_leaf': 99, 'reg_alpha': 0.0005173755450738341, 'reg_lambda': 0.054409371617615304, 'min_gain_to_split': 1.5196316938223222, 'subsample': 0.701721677161627, 'colsample_bytree': 0.6262297003286486, 'learning_rate': 0.015095826161521214, 'n_estimators': 999}. Best is trial 7 with value: 0.568651612260586.

Best trial: 23. Best value: 0.569617:  38%|███▊      | 23/60 [2:05:55<3:43:56, 363.15s/it]

[I 2026-06-06 20:17:58,939] Trial 23 finished with value: 0.5696168914882132 and parameters: {'num_leaves': 77, 'max_depth': 8, 'min_data_in_leaf': 102, 'reg_alpha': 0.01869117930084408, 'reg_lambda': 0.005863932149118866, 'min_gain_to_split': 0.23535160074243366, 'subsample': 0.7335090234500156, 'colsample_bytree': 0.7052002862532762, 'learning_rate': 0.01818234587191446, 'n_estimators': 978}. Best is trial 23 with value: 0.5696168914882132.

Best trial: 23. Best value: 0.569617:  40%|████      | 24/60 [2:08:53<3:04:37, 307.72s/it]

[I 2026-06-06 20:20:57,365] Trial 24 pruned.

Best trial: 23. Best value: 0.569617:  42%|████▏     | 25/60 [2:14:40<3:06:23, 319.54s/it]

[I 2026-06-06 20:26:44,494] Trial 25 finished with value: 0.5686295566254712 and parameters: {'num_leaves': 93, 'max_depth': 7, 'min_data_in_leaf': 98, 'reg_alpha': 0.047521556972236076, 'reg_lambda': 0.02245905692006259, 'min_gain_to_split': 0.26684712270622657, 'subsample': 0.7901089544730997, 'colsample_bytree': 0.6773252663654031, 'learning_rate': 0.017079462607273055, 'n_estimators': 799}. Best is trial 23 with value: 0.5696168914882132.

Best trial: 26. Best value: 0.569653:  43%|████▎     | 26/60 [2:20:46<3:08:52, 333.32s/it]

[I 2026-06-06 20:32:49,958] Trial 26 finished with value: 0.5696525522744655 and parameters: {'num_leaves': 89, 'max_depth': 9, 'min_data_in_leaf': 108, 'reg_alpha': 0.5696927628441495, 'reg_lambda': 0.018014854759574945, 'min_gain_to_split': 0.1054494758937731, 'subsample': 0.7658435838027686, 'colsample_bytree': 0.5865049982813844, 'learning_rate': 0.02104359654744066, 'n_estimators': 982}. Best is trial 26 with value: 0.5696525522744655.

Best trial: 26. Best value: 0.569653:  45%|████▌     | 27/60 [2:25:37<2:56:27, 320.85s/it]

[I 2026-06-06 20:37:41,707] Trial 27 finished with value: 0.5681922016588465 and parameters: {'num_leaves': 137, 'max_depth': 8, 'min_data_in_leaf': 95, 'reg_alpha': 0.6832795598534369, 'reg_lambda': 0.1403656651884248, 'min_gain_to_split': 0.3643500312567036, 'subsample': 0.7888160544762938, 'colsample_bytree': 0.5894971505647201, 'learning_rate': 0.031660612299071904, 'n_estimators': 989}. Best is trial 26 with value: 0.5696525522744655.

Best trial: 26. Best value: 0.569653:  47%|████▋     | 28/60 [2:28:16<2:25:08, 272.15s/it]

[I 2026-06-06 20:40:20,250] Trial 28 pruned.

Best trial: 26. Best value: 0.569653:  48%|████▊     | 29/60 [2:32:43<2:19:49, 270.63s/it]

[I 2026-06-06 20:44:47,312] Trial 29 pruned.

Best trial: 26. Best value: 0.569653:  50%|█████     | 30/60 [2:40:59<2:49:06, 338.22s/it]

[I 2026-06-06 20:53:03,251] Trial 30 finished with value: 0.5696440898140327 and parameters: {'num_leaves': 133, 'max_depth': 8, 'min_data_in_leaf': 117, 'reg_alpha': 0.8931951139264447, 'reg_lambda': 0.01448997628455774, 'min_gain_to_split': 0.6882014650930978, 'subsample': 0.7778021451031472, 'colsample_bytree': 0.6093450929223623, 'learning_rate': 0.013363945512973046, 'n_estimators': 1068}. Best is trial 26 with value: 0.5696525522744655.

Best trial: 31. Best value: 0.569772:  52%|█████▏    | 31/60 [2:49:39<3:09:48, 392.72s/it]

[I 2026-06-06 21:01:43,117] Trial 31 finished with value: 0.5697720946189407 and parameters: {'num_leaves': 128, 'max_depth': 9, 'min_data_in_leaf': 118, 'reg_alpha': 0.06352804004871407, 'reg_lambda': 0.004327208828582105, 'min_gain_to_split': 0.21081955931538124, 'subsample': 0.7156860908521643, 'colsample_bytree': 0.6956014536045366, 'learning_rate': 0.010204961718444407, 'n_estimators': 1052}. Best is trial 31 with value: 0.5697720946189407.

Best trial: 31. Best value: 0.569772:  53%|█████▎    | 32/60 [2:57:24<3:13:22, 414.38s/it]

[I 2026-06-06 21:09:28,054] Trial 32 finished with value: 0.567815577021246 and parameters: {'num_leaves': 125, 'max_depth': 11, 'min_data_in_leaf': 108, 'reg_alpha': 0.11051844440761172, 'reg_lambda': 0.01763367568480752, 'min_gain_to_split': 0.42769106675220125, 'subsample': 0.7014681492820595, 'colsample_bytree': 0.7756550382431127, 'learning_rate': 0.010286257110620447, 'n_estimators': 872}. Best is trial 31 with value: 0.5697720946189407.

Best trial: 31. Best value: 0.569772:  55%|█████▌    | 33/60 [3:07:50<3:35:06, 478.01s/it]

[I 2026-06-06 21:19:54,536] Trial 33 finished with value: 0.5696713268520899 and parameters: {'num_leaves': 170, 'max_depth': 8, 'min_data_in_leaf': 84, 'reg_alpha': 1.4803448162188744, 'reg_lambda': 0.0054515596678908745, 'min_gain_to_split': 0.500195334210174, 'subsample': 0.8329080153955825, 'colsample_bytree': 0.5071903727739651, 'learning_rate': 0.012056441099595527, 'n_estimators': 1116}. Best is trial 31 with value: 0.5697720946189407.

Best trial: 31. Best value: 0.569772:  57%|█████▋    | 34/60 [3:11:52<2:56:25, 407.14s/it]

[I 2026-06-06 21:23:56,306] Trial 34 pruned.

Best trial: 31. Best value: 0.569772:  58%|█████▊    | 35/60 [3:19:06<2:52:59, 415.18s/it]

[I 2026-06-06 21:31:10,259] Trial 35 finished with value: 0.5689838852142606 and parameters: {'num_leaves': 147, 'max_depth': 7, 'min_data_in_leaf': 114, 'reg_alpha': 0.07806423231680348, 'reg_lambda': 0.017538340418949215, 'min_gain_to_split': 0.031055294238298586, 'subsample': 0.7313970639924839, 'colsample_bytree': 0.6396580968664003, 'learning_rate': 0.012937282703975043, 'n_estimators': 1059}. Best is trial 31 with value: 0.5697720946189407.

Best trial: 31. Best value: 0.569772:  60%|██████    | 36/60 [3:28:05<3:00:58, 452.44s/it]

[I 2026-06-06 21:40:09,620] Trial 36 finished with value: 0.5688760774487532 and parameters: {'num_leaves': 125, 'max_depth': 7, 'min_data_in_leaf': 85, 'reg_alpha': 0.5578149617652685, 'reg_lambda': 0.002670203071581918, 'min_gain_to_split': 0.2982029085543387, 'subsample': 0.9135163105426709, 'colsample_bytree': 0.5376629368849457, 'learning_rate': 0.0120057879026604, 'n_estimators': 1043}. Best is trial 31 with value: 0.5697720946189407.

Best trial: 31. Best value: 0.569772:  62%|██████▏   | 37/60 [3:33:39<2:39:48, 416.89s/it]

[I 2026-06-06 21:45:43,583] Trial 37 pruned.

Best trial: 31. Best value: 0.569772:  63%|██████▎   | 38/60 [3:40:10<2:30:00, 409.12s/it]

[I 2026-06-06 21:52:14,570] Trial 38 finished with value: 0.5694195376023241 and parameters: {'num_leaves': 186, 'max_depth': 10, 'min_data_in_leaf': 107, 'reg_alpha': 0.5453669266177085, 'reg_lambda': 0.0823729282765387, 'min_gain_to_split': 0.5999955265596694, 'subsample': 0.8869319349765479, 'colsample_bytree': 0.7124287132223788, 'learning_rate': 0.014844280917883193, 'n_estimators': 832}. Best is trial 31 with value: 0.5697720946189407.

Best trial: 31. Best value: 0.569772:  65%|██████▌   | 39/60 [3:47:29<2:26:18, 418.03s/it]

[I 2026-06-06 21:59:33,376] Trial 39 finished with value: 0.5692356583116288 and parameters: {'num_leaves': 97, 'max_depth': 11, 'min_data_in_leaf': 120, 'reg_alpha': 0.10845402992946103, 'reg_lambda': 0.009110107665915733, 'min_gain_to_split': 0.4967660140312421, 'subsample': 0.7716931793336025, 'colsample_bytree': 0.6054801421183916, 'learning_rate': 0.011754393420724263, 'n_estimators': 1122}. Best is trial 31 with value: 0.5697720946189407.

Best trial: 31. Best value: 0.569772:  67%|██████▋   | 40/60 [3:49:50<1:51:40, 335.01s/it]

[I 2026-06-06 22:01:54,681] Trial 40 pruned.

Best trial: 31. Best value: 0.569772:  68%|██████▊   | 41/60 [3:53:16<1:33:51, 296.37s/it]

[I 2026-06-06 22:05:20,891] Trial 41 pruned.

Best trial: 31. Best value: 0.569772:  70%|███████   | 42/60 [3:57:53<1:27:10, 290.57s/it]

[I 2026-06-06 22:09:57,928] Trial 42 finished with value: 0.5688202128390575 and parameters: {'num_leaves': 129, 'max_depth': 9, 'min_data_in_leaf': 116, 'reg_alpha': 1.0006516436375876, 'reg_lambda': 0.003556468316243039, 'min_gain_to_split': 0.648931658315311, 'subsample': 0.7722628792799036, 'colsample_bytree': 0.542217731845191, 'learning_rate': 0.026191366834818767, 'n_estimators': 775}. Best is trial 31 with value: 0.5697720946189407.

Best trial: 31. Best value: 0.569772:  72%|███████▏  | 43/60 [4:04:50<1:33:01, 328.31s/it]

[I 2026-06-06 22:16:54,313] Trial 43 finished with value: 0.5690170218645563 and parameters: {'num_leaves': 118, 'max_depth': 8, 'min_data_in_leaf': 111, 'reg_alpha': 0.0993485136999879, 'reg_lambda': 0.004100793937819765, 'min_gain_to_split': 1.101610954466519, 'subsample': 0.8160424798987019, 'colsample_bytree': 0.6848522405222822, 'learning_rate': 0.012767789438503622, 'n_estimators': 1005}. Best is trial 31 with value: 0.5697720946189407.

Best trial: 31. Best value: 0.569772:  73%|███████▎  | 44/60 [4:14:18<1:46:43, 400.23s/it]

[I 2026-06-06 22:26:22,342] Trial 44 finished with value: 0.5693387937974679 and parameters: {'num_leaves': 163, 'max_depth': 8, 'min_data_in_leaf': 119, 'reg_alpha': 1.7694386223876137, 'reg_lambda': 0.0049995404754807505, 'min_gain_to_split': 0.7451291408096039, 'subsample': 0.8554254929506014, 'colsample_bytree': 0.5108946383074963, 'learning_rate': 0.01281453608274123, 'n_estimators': 1013}. Best is trial 31 with value: 0.5697720946189407.

Best trial: 31. Best value: 0.569772:  75%|███████▌  | 45/60 [4:19:45<1:34:35, 378.34s/it]

[I 2026-06-06 22:31:49,598] Trial 45 finished with value: 0.5682675696894075 and parameters: {'num_leaves': 59, 'max_depth': 10, 'min_data_in_leaf': 90, 'reg_alpha': 0.004892021377237826, 'reg_lambda': 0.08573978249611812, 'min_gain_to_split': 0.10328672963000554, 'subsample': 0.8109368643692013, 'colsample_bytree': 0.7052416684819852, 'learning_rate': 0.0165382391015479, 'n_estimators': 1040}. Best is trial 31 with value: 0.5697720946189407.

Best trial: 31. Best value: 0.569772:  77%|███████▋  | 46/60 [4:24:35<1:22:05, 351.86s/it]

[I 2026-06-06 22:36:39,664] Trial 46 pruned.

Best trial: 31. Best value: 0.569772:  78%|███████▊  | 47/60 [4:26:32<1:00:58, 281.46s/it]

[I 2026-06-06 22:38:36,858] Trial 47 pruned.

Best trial: 31. Best value: 0.569772:  80%|████████  | 48/60 [4:31:57<58:53, 294.43s/it]

[I 2026-06-06 22:44:01,543] Trial 48 finished with value: 0.568931071200487 and parameters: {'num_leaves': 144, 'max_depth': 10, 'min_data_in_leaf': 81, 'reg_alpha': 0.03093285533328211, 'reg_lambda': 0.00576328219387938, 'min_gain_to_split': 0.11954462430738738, 'subsample': 0.7582676917009215, 'colsample_bytree': 0.6432900526656694, 'learning_rate': 0.016870691653084163, 'n_estimators': 919}. Best is trial 31 with value: 0.5697720946189407.

Best trial: 31. Best value: 0.569772:  82%|████████▏ | 49/60 [4:34:34<46:23, 253.03s/it]

[I 2026-06-06 22:46:37,969] Trial 49 pruned.

Best trial: 50. Best value: 0.570053:  83%|████████▎ | 50/60 [4:42:15<52:35, 315.55s/it]

[I 2026-06-06 22:54:19,411] Trial 50 finished with value: 0.5700533452742491 and parameters: {'num_leaves': 118, 'max_depth': 7, 'min_data_in_leaf': 40, 'reg_alpha': 0.1885210600468343, 'reg_lambda': 0.18245157688621794, 'min_gain_to_split': 0.3205376221177295, 'subsample': 0.8313831030674474, 'colsample_bytree': 0.5783589264118796, 'learning_rate': 0.012102188789764785, 'n_estimators': 1036}. Best is trial 50 with value: 0.5700533452742491.

Best trial: 50. Best value: 0.570053:  85%|████████▌ | 51/60 [4:45:50<42:48, 285.41s/it]

[I 2026-06-06 22:57:54,483] Trial 51 pruned.

Best trial: 50. Best value: 0.570053:  87%|████████▋ | 52/60 [4:49:27<35:18, 264.77s/it]

[I 2026-06-06 23:01:31,097] Trial 52 pruned.

Best trial: 50. Best value: 0.570053:  88%|████████▊ | 53/60 [4:52:48<28:40, 245.80s/it]

[I 2026-06-06 23:04:52,638] Trial 53 pruned.

Best trial: 50. Best value: 0.570053:  90%|█████████ | 54/60 [4:55:46<22:32, 225.35s/it]

[I 2026-06-06 23:07:50,255] Trial 54 pruned.

Best trial: 50. Best value: 0.570053:  92%|█████████▏| 55/60 [4:59:55<19:21, 232.38s/it]

[I 2026-06-06 23:11:59,042] Trial 55 finished with value: 0.5685734146313352 and parameters: {'num_leaves': 86, 'max_depth': 8, 'min_data_in_leaf': 94, 'reg_alpha': 0.3070504444255207, 'reg_lambda': 0.0017159623500879217, 'min_gain_to_split': 0.20953350036418958, 'subsample': 0.782174662847233, 'colsample_bytree': 0.7532191014446892, 'learning_rate': 0.024808984168866784, 'n_estimators': 868}. Best is trial 50 with value: 0.5700533452742491.

Best trial: 50. Best value: 0.570053:  93%|█████████▎| 56/60 [5:03:24<15:01, 225.33s/it]

[I 2026-06-06 23:15:27,938] Trial 56 pruned.

Best trial: 50. Best value: 0.570053:  95%|█████████▌| 57/60 [5:05:45<10:00, 200.11s/it]

[I 2026-06-06 23:17:49,204] Trial 57 pruned.

Best trial: 50. Best value: 0.570053:  97%|█████████▋| 58/60 [5:10:38<07:36, 228.11s/it]

[I 2026-06-06 23:22:42,637] Trial 58 pruned.

Best trial: 50. Best value: 0.570053:  98%|█████████▊| 59/60 [5:14:33<03:50, 230.10s/it]

[I 2026-06-06 23:26:37,381] Trial 59 pruned.

Best trial: 50. Best value: 0.570053: 100%|██████████| 60/60 [5:17:34<00:00, 317.57s/it]

[I 2026-06-06 23:29:38,408] Trial 60 pruned.
Best trial: 50
Best Macro F1: 0.5700533452742491
Best params:
{
  "num_leaves": 118,
  "max_depth": 7,
  "min_data_in_leaf": 40,
  "reg_alpha": 0.1885210600468343,
  "reg_lambda": 0.18245157688621794,
  "min_gain_to_split": 0.3205376221177295,
  "subsample": 0.8313831030674474,
  "colsample_bytree": 0.5783589264118796,
  "learning_rate": 0.012102188789764785,
  "n_estimators": 1036
}

## 6. Exportacion de trials y parametros

Los resultados se guardan separados del modelo final congelado. Este notebook no sobrescribe `models/lgbm_bert_final.joblib`.

In [6]:
trials_df = study.trials_dataframe(attrs=("number", "value", "state", "params", "user_attrs", "duration"))
trials_path = OUT_DIR / "lgbm_bert_optuna_trials.csv"
trials_df.to_csv(trials_path, index=False, encoding="utf-8")

best_params = params_from_completed_trial(study.best_trial)
best_params["n_estimators"] = int(round(study.best_trial.user_attrs.get("best_iteration_mean", best_params["n_estimators"])))

best_payload = {
    "study_name": STUDY_NAME,
    "baseline_macro_f1_oof": BASELINE_MACRO_F1,
    "best_trial_number": int(study.best_trial.number),
    "best_macro_f1_oof": float(study.best_value),
    "improvement_vs_baseline": float(study.best_value - BASELINE_MACRO_F1),
    "best_params_raw_trial": study.best_trial.params,
    "best_params_lgbm": best_params,
    "best_user_attrs": study.best_trial.user_attrs,
    "n_trials_total_in_study": len(study.trials),
    "test_usage": "No se carga ni se usa test temporal en este notebook.",
}

best_path = OUT_DIR / "lgbm_bert_optuna_best_params.json"
best_path.write_text(json.dumps(best_payload, ensure_ascii=False, indent=2), encoding="utf-8")

print(f"Trials -> {trials_path}")
print(f"Best params -> {best_path}")

Trials -> C:\Users\CARLOS\triaje-ia-tfg\reports\hyperparameter_tuning\lgbm_bert_optuna_trials.csv
Best params -> C:\Users\CARLOS\triaje-ia-tfg\reports\hyperparameter_tuning\lgbm_bert_optuna_best_params.json

## 7. Comparacion contra el modelo congelado

La comparacion se hace contra el resultado OOF ya congelado en el notebook 07. Si la mejora no es clara o empeora clases sensibles, se mantiene el modelo actual.

In [ ]:
baseline_row = {
    "modelo": "lightgbm_final_bert_actual",
    "macro_f1": 0.567940,
    "recall_a1": 0.687523,
    "precision_a1": 0.652363,
    "recall_a2": 0.654815,
    "precision_a2": 0.669934,
    "best_iteration_mean": 491.2,
}

best_attrs = study.best_trial.user_attrs
optuna_row = {
    "modelo": "lightgbm_final_bert_optuna",
    "macro_f1": float(study.best_value),
    "recall_a1": best_attrs.get("recall_a1"),
    "precision_a1": best_attrs.get("precision_a1"),
    "recall_a2": best_attrs.get("recall_a2"),
    "precision_a2": best_attrs.get("precision_a2"),
    "best_iteration_mean": best_attrs.get("best_iteration_mean"),
}

comparison = pd.DataFrame([baseline_row, optuna_row])
comparison["delta_macro_f1_vs_actual"] = comparison["macro_f1"] - BASELINE_MACRO_F1
comparison

,modelo,macro_f1,recall_a1,precision_a1,recall_a2,precision_a2,best_iteration_mean,delta_macro_f1_vs_actual
0,lightgbm_final_bert_actual,0.567940,0.687523,0.652363,0.654815,0.669934,491.2,0.000000
1,lightgbm_final_bert_optuna,0.570053,0.685767,0.650698,0.653305,0.668943,1035.6,0.002113

:

In [ ]:
summary_path = OUT_DIR / "lgbm_bert_optuna_summary.md"
improvement = float(study.best_value - BASELINE_MACRO_F1)
decision = (
    "La configuracion Optuna mejora el OOF del modelo actual y puede considerarse candidata, "
    "pendiente de congelacion y evaluacion final controlada."
    if improvement > 0.001
    else "La mejora no es suficientemente clara; se mantiene el modelo congelado actual."
)

comparison_md = comparison.to_csv(index=False, float_format="%.6f")

lines = [
    "# Busqueda Optuna LightGBM+BERT/SVD",
    "",
    "Busqueda de hiperparametros realizada exclusivamente sobre train con validacion cruzada agrupada por paciente. El test temporal no se ha usado para seleccionar parametros.",
    "",
    "## Configuracion",
    "",
    f"- Estudio: `{STUDY_NAME}`",
    f"- Trials totales en el estudio: {len(study.trials)}",
    f"- Folds: {N_SPLITS}",
    "- Metrica objetivo: Macro F1 OOF",
    "- Modelo: LightGBM + variables tabulares finales + BERT/SVD",
    "",
    "## Comparacion",
    "",
    "```csv",
    comparison_md.strip(),
    "```",
    "",
    "## Mejor trial",
    "",
    f"- Trial: {study.best_trial.number}",
    f"- Macro F1 OOF: {study.best_value:.6f}",
    f"- Mejora frente al actual: {improvement:+.6f}",
    f"- Recall A1: {best_attrs.get('recall_a1', float('nan')):.6f}",
    f"- Precision A1: {best_attrs.get('precision_a1', float('nan')):.6f}",
    f"- Recall A2: {best_attrs.get('recall_a2', float('nan')):.6f}",
    f"- Precision A2: {best_attrs.get('precision_a2', float('nan')):.6f}",
    "",
    "## Lectura metodologica",
    "",
    decision,
    "",
    "No se sobrescribe el modelo final actual. Si esta configuracion se adopta, debe congelarse primero con todo train y solo despues evaluarse una vez en test temporal.",
    "",
    "## Parametros ganadores",
    "",
    "```json",
    json.dumps(best_params, ensure_ascii=False, indent=2),
    "```",
    "",
    "## Artefactos",
    "",
    f"- Trials: `{trials_path.relative_to(PROJECT_ROOT)}`",
    f"- Parametros: `{best_path.relative_to(PROJECT_ROOT)}`",
    f"- Resumen: `{summary_path.relative_to(PROJECT_ROOT)}`",
    "",
    "## Nota para la memoria",
    "",
    "Este experimento puede citarse como una prueba adicional de ajuste posterior a la seleccion de arquitectura. La seleccion sigue basandose en OOF/train, no en test.",
]
summary_path.write_text("\n".join(lines), encoding="utf-8")
print(f"Resumen -> {summary_path}")

## 9. Cierre

Este notebook deja documentada la busqueda de hiperparametros del ganador. El siguiente paso solo debe ejecutarse si se decide adoptar el candidato: reentrenar con todo train, congelar artefactos nuevos y evaluar una unica vez en el test temporal.